import { imageService, ImageServiceError, type ImageJobRead, type ImageJobStatus, type ImageQualityPreset } from '$lib/api/imageService';
import { settingsStore } from '$lib/stores/settingsStore';
import { ttsStore } from '$lib/stores/ttsStore.svelte';
import type { ChatMessage } from '$lib/types/chat';
import type { ResolvedVisualNovelScene } from '$lib/types/visualNovel';

export type ImageGenerationSource = 'chat' | 'visual-novel' | 'auto-chat' | 'auto-vn';
export type ImageDisplayMode = 'chat-card' | 'vn-overlay' | 'vn-background';

export interface ImageGenerationJob {
  id: string;
  source: ImageGenerationSource;
  displayMode: ImageDisplayMode;
  messageId?: string;
  title: string;
  prompt: string;
  status: ImageJobStatus | 'submitting';
  progress: number;
  phase: string;
  message: string;
  outputUrls: string[];
  createdAt: Date;
  updatedAt: Date;
  resourceMode: string;
  activePreset: ImageQualityPreset;
  requestedPreset: ImageQualityPreset;
  fallbackUsed: boolean;
  vramFreeMb?: number | null;
  vramRequiredMb?: number | null;
  error?: string | null;
}

interface PendingJobMetadata {
  source: ImageGenerationSource;
  displayMode: ImageDisplayMode;
  messageId?: string;
  title: string;
}

const TERMINAL_STATUSES: Array<ImageGenerationJob['status']> = ['completed', 'failed', 'cancelled'];
const DEFAULT_PRESET: ImageQualityPreset = 'preview_8gb';
const MAX_PROMPT_CHARS = 1_000;
const MAX_ACTIVE_JOBS = 8;

const clipPrompt = (prompt: string): string => prompt.trim().replace(/\s+/g, ' ').slice(0, MAX_PROMPT_CHARS);

const statusIsTerminal = (status: ImageGenerationJob['status']): boolean => TERMINAL_STATUSES.includes(status);

const friendlyImageError = (error: unknown): string => {
  if (error instanceof ImageServiceError) {
    if (error.code === 'image_cancelled') return 'Image generation was cancelled.';
    if (error.code === 'image_generation_disabled') return 'Image generation is disabled in the local backend.';
    if (error.code === 'image_backend_unavailable') return error.message;
    if (error.retryable) return `${error.message} You can try again after local resources settle.`;
    return error.message;
  }
  return 'Image generation could not start. Chat and voice are unaffected.';
};

const promptFromMessage = (message: ChatMessage): string => {
  const roleHint = message.role === 'assistant' ? 'Visualize Reverie in this scene:' : 'Visualize the user-described scene:';
  return clipPrompt(`${roleHint} ${message.content}`);
};

const promptFromScene = (scene: ResolvedVisualNovelScene, latestLine: string): string =>
  clipPrompt(
    `Visualize this visual novel scene with Reverie: ${scene.manifest.characterName}, ${scene.expressionLabel} expression, ${scene.poseLabel.toLowerCase()} pose. Current line: ${latestLine}`
  );

class ImageGenerationStore {
  jobs = $state<Record<string, ImageGenerationJob>>({});
  orderedIds = $state<string[]>([]);
  expandedJobId = $state<string | null>(null);
  announcement = $state('Image generation is ready.');
  autoGenerateChat = $state(settingsStore.getSnapshot().imageAutoGenerateChat);
  autoGenerateVisualNovel = $state(settingsStore.getSnapshot().imageAutoGenerateVisualNovel);

  private controllers = new Map<string, AbortController>();
  private autoGeneratedMessageIds = new Set<string>();

  constructor() {
    settingsStore.subscribe((settings) => {
      this.autoGenerateChat = settings.imageAutoGenerateChat;
      this.autoGenerateVisualNovel = settings.imageAutoGenerateVisualNovel;
    });
  }

  get activeJobs() {
    return this.orderedIds.map((id) => this.jobs[id]).filter((job) => job && !statusIsTerminal(job.status));
  }

  get hasActiveJobs() {
    return this.activeJobs.length > 0;
  }

  get resourceLabel() {
    if (ttsStore.presenceState === 'speaking' || ttsStore.presenceState === 'preparing') {
      return 'Images will wait while Reverie is speaking.';
    }
    if (this.hasActiveJobs) return 'Image generation is running as a low-priority local job.';
    return 'Image generation is ready and will yield to voice playback.';
  }

  get latestVisualNovelJob() {
    return this.orderedIds.map((id) => this.jobs[id]).find((job) => job?.source.includes('vn') || job?.source === 'visual-novel') ?? null;
  }

  jobsForMessage(messageId: string): ImageGenerationJob[] {
    return this.orderedIds.map((id) => this.jobs[id]).filter((job) => job?.messageId === messageId);
  }

  latestCompletedForMessage(messageId: string): ImageGenerationJob | null {
    return this.jobsForMessage(messageId).find((job) => job.status === 'completed' && job.outputUrls.length > 0) ?? null;
  }

  toggleExpanded(jobId: string) {
    this.expandedJobId = this.expandedJobId === jobId ? null : jobId;
  }

  maybeAutoGenerateFromMessage(message: ChatMessage) {
    if (!this.autoGenerateChat || message.role !== 'assistant' || message.status === 'streaming' || this.autoGeneratedMessageIds.has(message.id)) {
      return;
    }
    this.autoGeneratedMessageIds.add(message.id);
    void this.generateFromMessage(message, { source: 'auto-chat' });
  }

  async generateFromMessage(message: ChatMessage, options: { source?: ImageGenerationSource } = {}) {
    const prompt = promptFromMessage(message);
    if (!prompt) return;

    await this.enqueue({
      prompt,
      source: options.source ?? 'chat',
      displayMode: 'chat-card',
      messageId: message.id,
      title: message.role === 'assistant' ? 'Generated from Reverie’s reply' : 'Generated from your message',
      context: {
        source: options.source ?? 'chat',
        message_id: message.id,
        role: message.role,
        tts_presence: ttsStore.presenceState,
        visual_state: message.visualState ?? null,
        tts_context: message.tts?.ttsContext ?? null
      }
    });
  }

  async visualizeScene(scene: ResolvedVisualNovelScene, latestLine: string, options: { source?: ImageGenerationSource } = {}) {
    await this.enqueue({
      prompt: promptFromScene(scene, latestLine),
      source: options.source ?? 'visual-novel',
      displayMode: 'vn-overlay',
      title: 'Visual novel scene image',
      context: {
        source: options.source ?? 'visual-novel',
        character_name: scene.manifest.characterName,
        expression: scene.state.expression,
        pose: scene.state.pose,
        background: scene.state.background,
        latest_line: latestLine,
        tts_presence: ttsStore.presenceState
      }
    });
  }

  async cancel(jobId: string) {
    this.controllers.get(jobId)?.abort();
    try {
      const job = await imageService.cancelJob(jobId);
      this.applyBackendJob(job, this.jobs[jobId]);
    } catch (error) {
      this.patchJob(jobId, { status: 'cancelled', error: friendlyImageError(error), message: 'Image job cancelled.' });
    }
  }

  private async enqueue(input: {
    prompt: string;
    source: ImageGenerationSource;
    displayMode: ImageDisplayMode;
    title: string;
    messageId?: string;
    context?: Record<string, unknown>;
  }) {
    const localId = `pending-image-${Date.now()}-${Math.random().toString(36).slice(2)}`;
    const now = new Date();
    const metadata: PendingJobMetadata = {
      source: input.source,
      displayMode: input.displayMode,
      messageId: input.messageId,
      title: input.title
    };

    this.upsertJob(localId, {
      id: localId,
      source: input.source,
      displayMode: input.displayMode,
      messageId: input.messageId,
      title: input.title,
      prompt: input.prompt,
      status: 'submitting',
      progress: 0,
      phase: 'submitting',
      message: ttsStore.isSpeaking ? 'Queued locally; waiting for voice to finish before image work starts.' : 'Sending image request to the local queue.',
      outputUrls: [],
      createdAt: now,
      updatedAt: now,
      resourceMode: ttsStore.isSpeaking ? 'paused_for_tts' : 'submitting',
      activePreset: DEFAULT_PRESET,
      requestedPreset: DEFAULT_PRESET,
      fallbackUsed: false
    });
    this.announcement = 'Image request queued without blocking chat or voice.';

    try {
      const response = await imageService.generateImage({
        prompt: input.prompt,
        context: input.context,
        quality_preset: DEFAULT_PRESET
      });
      this.replaceJobId(localId, response.job, metadata);
      this.watchJob(response.job.job_id);
    } catch (error) {
      this.patchJob(localId, {
        status: 'failed',
        phase: 'failed',
        progress: 1,
        error: friendlyImageError(error),
        message: friendlyImageError(error),
        updatedAt: new Date()
      });
      this.announcement = friendlyImageError(error);
    }
  }

  private watchJob(jobId: string) {
    const controller = new AbortController();
    this.controllers.set(jobId, controller);
    void imageService
      .streamJobEvents(
        jobId,
        {
          onEvent: (event) => {
            this.patchJob(jobId, {
              status: event.status,
              progress: event.progress,
              phase: event.phase,
              message: event.message,
              outputUrls: event.output_paths.map((path) => imageService.getImageUrl(jobId, path)),
              resourceMode: event.resource_mode ?? this.jobs[jobId]?.resourceMode ?? 'queued',
              fallbackUsed: event.fallback_used ?? false,
              vramFreeMb: event.vram_free_mb,
              vramRequiredMb: event.vram_required_mb,
              error: event.error?.message ?? null,
              updatedAt: new Date(event.timestamp)
            });
            this.announcement = event.message;
            if (TERMINAL_STATUSES.includes(event.status)) this.controllers.delete(jobId);
          }
        },
        { signal: controller.signal }
      )
      .catch((error) => {
        if (controller.signal.aborted) return;
        this.patchJob(jobId, { status: 'failed', phase: 'failed', error: friendlyImageError(error), message: friendlyImageError(error) });
        this.controllers.delete(jobId);
      });
  }

  private replaceJobId(localId: string, backendJob: ImageJobRead, metadata: PendingJobMetadata) {
    const previous = this.jobs[localId];
    delete this.jobs[localId];
    this.orderedIds = this.orderedIds.map((id) => (id === localId ? backendJob.job_id : id));
    this.applyBackendJob(backendJob, previous ? { ...previous, ...metadata, id: backendJob.job_id } : undefined, metadata);
    this.trimCompletedJobs();
  }

  private applyBackendJob(backendJob: ImageJobRead, previous?: ImageGenerationJob, metadata?: PendingJobMetadata) {
    this.upsertJob(backendJob.job_id, {
      id: backendJob.job_id,
      source: metadata?.source ?? previous?.source ?? 'chat',
      displayMode: metadata?.displayMode ?? previous?.displayMode ?? 'chat-card',
      messageId: metadata?.messageId ?? previous?.messageId,
      title: metadata?.title ?? previous?.title ?? 'Generated image',
      prompt: backendJob.prompt,
      status: backendJob.status,
      progress: backendJob.progress,
      phase: backendJob.phase,
      message: backendJob.message,
      outputUrls: backendJob.output_paths.map((path) => imageService.getImageUrl(backendJob.job_id, path)),
      createdAt: new Date(backendJob.created_at),
      updatedAt: new Date(backendJob.updated_at),
      resourceMode: backendJob.resource_mode ?? 'queued',
      activePreset: backendJob.active_preset,
      requestedPreset: backendJob.requested_preset,
      fallbackUsed: backendJob.fallback_used ?? false,
      vramFreeMb: backendJob.vram_free_mb,
      vramRequiredMb: backendJob.vram_required_mb,
      error: backendJob.error?.message ?? null
    });
  }

  private upsertJob(id: string, job: ImageGenerationJob) {
    this.jobs[id] = job;
    if (!this.orderedIds.includes(id)) this.orderedIds = [id, ...this.orderedIds];
  }

  private patchJob(id: string, patch: Partial<ImageGenerationJob>) {
    const existing = this.jobs[id];
    if (!existing) return;
    this.jobs[id] = { ...existing, ...patch, updatedAt: patch.updatedAt ?? new Date() };
  }

  private trimCompletedJobs() {
    if (this.orderedIds.length <= MAX_ACTIVE_JOBS) return;
    this.orderedIds = this.orderedIds.filter((id, index) => index < MAX_ACTIVE_JOBS || !statusIsTerminal(this.jobs[id]?.status));
  }
}

export const imageGenerationStore = new ImageGenerationStore();
